[general]
log_level = "info"
log_dir = "{{.Log}}"

[ca_server]
listen = "0.0.0.0:5000"
server_id = "Shell Vault CA"
allowed_key_types = [ "ecdsa", "ed25519" ]
# After this many seconds the server will automatically rotate the certs private key
# and publish the new key
root_key_type = "ed25519"
root_key_max_ttl = 2592000
user_cert_ttl = 72000

[providers.local_keychain_provider]
fs = "local"
ttl_tick = 60

[providers.auth_provider]
realm="local"

[providers.auth_providers.pam]
allowed_groups=["*"]

[admin_server]
listen = "localhost:8000"
