[logging]
put_to_files = false

[logging.encoder_config]
message_key = "message"
level_key = "level"
level_encoder = "lowercase"


[ca_server]
listen = "0.0.0.0:5000"
server_id = "test_server"
allowed_key_types = [ "ecdsa", "ed25519" ]
# After this many seconds the server will automatically rotate the certs private key
# and publish the new key
root_key_type = "ed25519"
# The default key will be valid for a whole year
root_key_max_ttl = 31104000
user_cert_ttl = 72000
auth_session_ttl = 72000

[ca_server.authorizers]
allowed_plugins = ["allowall.expr"]
request_user_certificate = "allowall"
request_host_certificate = "allowall"

[providers.local_keychain_provider]
path = "./certstore"
fs = "local"
ttl_tick = 60

[providers.auth_provider]
realm="local"

[providers.auth_providers.pam]
allowed_groups=["*"]

[admin_server]
listen = "localhost:8000"
auth_session_ttl = 3600
