[ca_server]
listen = "0.0.0.0:5000"
server_id = "test_server"
allowed_key_types = [ "ecdsa", "ed25519" ]
# After this many seconds the server will automatically rotate the certs private key
# and publish the new key
root_key_type = "ed25519"
root_key_max_ttl = 2592000
user_cert_ttl = 72000

[providers.local_keychain_provider]
path = "./certstore"
fs = "local"
ttl_tick = 60

[providers.auth_provider]
realm="local"

[providers.auth_providers.pam]
allowed_groups=["*"]

[admin_server]
listen = "localhost:8000"
root_key = "AAAAC3NzaC1lZDI1NTE5AAAAIAhOhkaucaaXC18WrhZUti7mZP4466MqPjXSDukCUBPk"
