name = "Base local auth provider rules"
version = "1.0.0"
author = "StatePrism"
description = "Allow any user to get a user certificate, allow only root to get host certificates"

[[sources]]
file = "all_users.expr"
applies_to = ["/CertificateAuthority/RequestUserCertificate"]

[[sources]]
file = "only_root.expr"
applies_to = ["/CertificateAuthority/RequestUserCertificate"]
